### ISSUE TITLE
cannot connect to omero

### ISSUE THREAD

**Issue by CFGrote** [mstritt/orbit-image-analysis#11]
hi,
trying to run orbit v363 on debian10.

installed to /opt/orbit

```
$> /opt/orbit/orbit.sh
```
 launches the orbit gui but i get this message:

![image](https://user-images.githubusercontent.com/15476807/83162378-f8d97580-a109-11ea-8572-4c5cfe6cf634.png)

The complete startup log:

```
$> /opt/orbit/orbit.sh                                    
17:39:48,657 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:39:48,657 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:39:48,658 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/orbit/lib/image-provider-omero-1.7.2.jar!/logback.xml]
17:39:48,658 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
17:39:48,658 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/orbit/lib/orbit-image-analysis.jar!/logback.xml]
17:39:48,658 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/orbit/lib/image-provider-omero-1.7.2.jar!/logback.xml]
17:39:48,675 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6236eb5f - URL [jar:file:/opt/orbit/lib/image-provider-omero-1.7.2.jar!/logback.xml] is not of type file
17:39:48,745 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:39:48,754 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to WARN
17:39:48,754 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [httpclient] to WARN
17:39:48,754 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:39:48,755 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7c1e2a9e - Registering current configuration as safe fallback point

java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.actelion.research.orbit.imageAnalysis.dal.DALConfig.<clinit>(DALConfig.java:79)
	at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis.getInfoString(OrbitImageAnalysis.java:794)
	at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis.<init>(OrbitImageAnalysis.java:281)
	at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis.getInstance(OrbitImageAnalysis.java:2782)
	at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis.lambda$initSingleApplication$7(OrbitImageAnalysis.java:2864)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Orbit Image Analysis Version  3.63
Copyright (c) 2009-2020, Idorsia Pharmaceuticals Ltd. under GPLv3 license.
Developed by Manuel Stritt and Jonathan Fuller.

Login User: guest
Available temporary disk space: 8698 MB.
Tile memory size (Read): 0 tiles
Tile memory capacity (Write): 788 MB
Tile temp directory: /tmp
JVM Memory used/total: 248 / 3940 MB
Available Cores: 8
JVM version: 11.0.7+10
Lib directory: /opt/orbit/lib
Loaded model: none

Optional parameters: [.orbit|image file(.jpg,.tif,.bmp,.png,.gif,.svs)|url|rdf id  ]
use -noErrorPopups to get rid of error popups (can be useful if you have no network connection)

use --hideQuickSearch to hide the left search bar (can be useful if you have no network connection)
```

And my ~/OrbitOmero.properties:
```
#Orbit Omero Config
OmeroHost=undisclosed.server.domain
SearchLimit=1000
UseSSL=false
OmeroPort=4064
OmeroWebPort=80
```

Any help would be appreciated.

**Comment by CFGrote** [comment]
And of course I checked that the omero server is online and I can login to the web interface and omero.insight

**Comment by mstritt** [comment]
Hi @CFGrote ,
I can have a closer look on it tomorrow, but Omero Port 4064 is for ssl, so either set usessl to true or set port to 4063 (no encryption). Can you please try?
Regards,
Manuel

**Comment by CFGrote** [comment]
hi @mstritt ,
thanks for the quick reply. i tested all combinations of ssl=true/false and port 4064/4063 and always got the same message posted above.

when i log in to omero-web, the connection is not encrypted (for reasons beyond this scope) and omero runs on port 4064 on the same host as omero-web.

**Comment by mstritt** [comment]
Dear  @CFGrote ,
I'm trying to reproduce...
So when you see the popup window and click on "Continue" - what happens then? Does Orbit start in standalone mode (without Omero connection) or does it crash?
Regards,
Manuel

**Comment by CFGrote** [comment]
it starts in standalone modus. i can't manualy login (File->Login) either.

**Comment by mstritt** [comment]
can you please try to create an OrbitOmero.properties.template  file in your usse home?
e.g. 
touch ~/OrbitOmero.properties.template
and retry?

**Comment by CFGrote** [comment]
i did, no success. same error log, same popup.

i had to change to the omero demo server because our instance is down
for maintenance over the weekend:

OmeroHost=ome-demoserver.openmicroscopy.org
SearchLimit=10000
UseSSL=true
OmeroPort=4064
OmeroWebPort=80

**Comment by mstritt** [comment]
Dear @CFGrote ,
we really tested a lot but always came to the same conclusion that your error appears if the OMERO connection parameters are not correct.
Can you please try to set
OmeroWebPort=4080
for the OME demo server?

Regards,
Manuel

**Comment by mstritt** [comment]
@CFGrote , Orbit first checks in the current (installation) directory and then in your user home directory and searches for the OrbitOmero.properties file. 
Maybe you edit the one in you user-home but have an existing (non-valid) file in the install directory?
Regards,
Manuel

**Comment by CFGrote** [comment]
hi,
first, thanks for your efforts. i tried with these settings:

```
#Orbit Omero Config
OmeroHost=demo.openmicroscopy.org
SearchLimit=10000
UseSSL=false
OmeroPort=4080
OmeroWebPort=80
```

and

```
#Orbit Omero Config
OmeroHost=demo.openmicroscopy.org
SearchLimit=10000
UseSSL=true
OmeroPort=4080
OmeroWebPort=80
```

to no avail. always the same error message and orbit client in
standalone mode.

**Comment by CFGrote** [comment]
i ran a

```
find /opt/orbit -name OrbitOmero.properties
```
which did not return anything.

**Comment by mstritt** [comment]
I think it should be

#Orbit Omero Config
OmeroHost=demo.openmicroscopy.org
SearchLimit=10000
UseSSL=true
OmeroPort=4064
OmeroWebPort=4080

Regards,
Manuel

**Comment by CFGrote** [comment]
Now i made some interesting observations:

i installed orbit-363 on a debian10 box that had never seen orbit
before:

```
cd /tmp
wget http://www.stritt.de/files/orbit_linux_363.tar.gz
mkdir orbit
cd orbit
tar xzvf ../orbit_linux_363.tar.gz
sudo ./install.sh

cd
/opt/orbit/orbit.sh
```

with this OrbitOmero.properties in $HOME (targeting our local omero
instance).
```
#Orbit Omero Config
OmeroHost=undisclosed.server.domain
SearchLimit=10000
UseSSL=true
OmeroPort=4064
OmeroWebPort=4080
```

It worked! I get the login screen, enter UN and PW and orbit launches
and is connected to the omero server.
So I have to set the omero web port to 4080.

Now the interesting part:

Remove the installation directory:
```
rm -r /tmp/orbit
```

Check orbit runs:
```
/opt/orbit/orbit.sh
```

-> orbit starts normally.


Remove the tar.gz
```
rm /tmp/orbit_linux_363.tar.gz
```

check again:
```
/opt/orbit/orbit.sh
```
-> bam, the old problem, orbit starts in standalone mode.

I reproduced this behaviour three times: As soon as I remove the
downloaded tar.gz (or move it somewhere else), I only get the
standalone orbit client. When putting the tar.gz back, I get the client
connected to omero.

Removing only the install directory (/tmp/orbit) in above example) has
no effect.

Hope this helps to address the problem.



n 6/3/20 4:53 PM, Manuel wrote:
> I think it should be
>
> #Orbit Omero Config
> OmeroHost=demo.openmicroscopy.org
> SearchLimit=10000
> UseSSL=true
> OmeroPort=4064
> OmeroWebPort=4080
>
> Regards,
> Manuel
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
>
<https://github.com/mstritt/orbit-image-analysis/issues/11#issuecomment-638250694>,

**Comment by mstritt** [comment]
thanks a lot @CFGrote for digging into this. We're currently having a loot into it - seems to something really wired.
Can you please test what happens if you simply call start-orbit.sh within the temp dir (extracted tar.gz folder). ?

Regards,
Manuel

**Comment by CFGrote** [comment]
Same observation: With the tar.gz file present in the location where it
was extracted from, `orbit-start.sh` brings up the GUI and connects to
omero. When tar.gz file removed, client goes to standalone mode.

**Comment by mstritt** [comment]
Orbit version 3.64 is out which hopefully fixes this bug. Can you please give it a try?
Manuel

**Comment by CFGrote** [comment]
thanks, 3.64 solves the issue for me. orbit starts up, connects to the
omero server configured in ~/OrbitOmere.properties. Same if installation
dir and tar.gz removed.
