### ISSUE TITLE
Request of One Image to Test the script

### ISSUE THREAD

**Issue by GiovannaMariaDimitri** [mstritt/orbit-image-analysis#15]
Hi Manuel, 

would it be possible to have one sample image to test your segmentation script? 

Thanks

Giovanna

**Comment by mstritt** [comment]
Dear Giovanna,
we don't have a sample image dataset (yet), but in principal you can take any e.g. DAPI image, e.g. [this one](https://upload-forum-cellprofiler-org.s3-us-west-2.amazonaws.com/original/2X/3/35f8d63434964b162ff6a54e8a742a6debfad45f.jpg).
Regards,
Manuel

**Comment by GiovannaMariaDimitri** [comment]
Dear Manuel,

thanks! 
I have just tried, and using this image and the pre-trained network you uploaded the result is a mask which has no labels. 
Can you help me out?
-This is the model I am using downloaded from your webpage: 20180202_glomeruli_detection_noquant.pb
-I am attaching for you the script I am using (which is your script) and the resized image you sent me cropped 512X512 as requested by the script

The model loads, correctly, but no labels are found. 

Thanks so much for your help! 

Giovanna 
[Archive.zip](https://github.com/mstritt/orbit-image-analysis/files/4787014/Archive.zip)

**Comment by mstritt** [comment]
Dear @GiovannaMariaDimitri ,
sorry this was a missunderstanding. The sample image was for "normal" segmentation, not glomeruli segmentation.
For that you need an kidney whole slide image.
Currently I cannot provide a sample image for that.
Regards,
Manuel

**Comment by GiovannaMariaDimitri** [comment]
Thank you Manuel. 
I have actually tried on mine, and it doesn't work. 
I have found an image, which are freely available on github: https://github.com/TheJacksonLaboratory/Digital-Glomerular-identification/tree/master/GlomIDTrainingImages

Could you please the functioning of your script with one of those? 

Thanks

Giovanna

**Comment by mstritt** [comment]
Dear @GiovannaMariaDimitri ,
these are not WSI images, only ROIs of it. This script works with WSI images (pyramidal), e.g. NDPI or SVS images.
Regards,
Manuel

**Comment by GiovannaMariaDimitri** [comment]
Dear Manuel, 

great thanks for your answer. 
However I have now a question. 
In all of the documentation you talk about 512X512 jpg images. And in fact the script segmentation.py takes as input the 512X512 jpg images. 
So if I have a 512X512 jpg image, already extracted from a multi-resolution one like a tiff, or a NDPI it should work, right? 
Also which would be therefore the previous step to perform, if I have the multi-resolution one, is it in your scripts? 

Thanks for your help, 
Hope you are having a great day

Kind regards

Giovanna 

p.s.: Also just as as an add up to this, in the summary there is the specification jpg for images and png for masks

**Comment by mstritt** [comment]
Dear @GiovannaMariaDimitri ,
for this you would have to dig into the java code (DlSegment class).
But what just came into my mind is that you could use our published glomeruli dataset:
https://doi.org/10.5061/dryad.fqz612jpc
from our orbit paper:
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007313

Hope that helps.

Regards,
Manuel
