### ISSUE TITLE
Deep Learning Model Upload sqlite annotations

### ISSUE THREAD

**Issue by GiovannaMariaDimitri** [mstritt/orbit-image-analysis#16]
Hi Manuel, 

I have downaloded the public available repository with the mice images and annotations. 
However I have a problem in uploading the annotations. 
The annotations are in the orbit.db file which you realeased. 
In the readme file it says it can be placed in the user-home to be automatically detected by the software. 
I have installed locally orbit, created a folder where there is the orbit.db file, one image. But when I open it with orbit, I see the image, but no annotation. 
How can I upload the orbit.db file? 
Thanks
Giovanna

**Comment by mstritt** [comment]
Dear @GiovannaMariaDimitri ,
the orbit.db file has to be placed in your user-home (under windows e.g. C:\Users\<username> ), not in the same folder as the images are.
Does that work for you?
Regards,
Manuel

**Comment by GiovannaMariaDimitri** [comment]
Hi Manuel, 

thanks! I am using mac, but now I have solved this issue. 
I have another question concerning the masks. But I will open another thread, cause is another topic. 

Thanks!
Giovanna
