### ISSUE TITLE
Sharing the glomeruli mask data

### ISSUE THREAD

**Issue by huuquan1994** [mstritt/orbit-image-analysis#23]
Hi Manuel,

Thanks so much for your work of sharing the meaningful WSI mice glomeruli dataset.
Since the segmentation data is in SQLite format, obtaining the mask data for training deep learning models is a bit inconvenient. Therefore, I extracted the segmentation data in JSON format for everyone's convenience. I hope you don't mind this. 
Link download: https://drive.google.com/file/d/1rXacSs_7e3cnbHpHttTn539U1f_MgSEq/view?usp=sharing

Check out my repo [here](https://github.com/huuquan1994/wsi_glomerulus_seg) for more details.

Best regards,

**Comment by mstritt** [comment]
nice! thanks a lot .
Manuel
