### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by aspergatus** [mstritt/orbit-image-analysis#3]
Hi Orbit Team,

When I am working with  big Image (100MB jpg), the program takes up a mount of memory when the image is loaded. But afterwards, The amount of memory used keeped increasing up to 5GB, even when you are not doing anything. I think memory usage is accelerated when you move around the image.

Could you have a look into it please.

Thanks,
Tony Nguyen

**Comment by mstritt** [comment]
Dear Tony,
this is answered here: https://forum.image.sc/t/orbit-memory-settings/24014
Regards,
Manuel

**Comment by aspergatus** [comment]
Hi Manuel,

I read your instruction for memory setting. But actually it does not solve my the issue. I have a PC with 24GB RAM, and still after a while Orbit uses up a lot of memory. I think there is a general memory leakage.
