### ISSUE TITLE
TileMode = false by default

### ISSUE THREAD

**Issue by aspergatus** [mstritt/orbit-image-analysis#5]
Hi Manuel,

I just saw that the TileMode is set to false by default. If I am not wrong, this will cause Orbit to load the whole Image into memory and not using Tile. Is there an advantage when TileMode is set to true?

Best, Tony

**Comment by mstritt** [comment]
Hi Tony,
if tilemode is false it also loads the border tiles to compute features for border pixels. Thats fine.
What might take time is rendering the classification mask overlay, which is ok. Simply drag the slider at the image button to the left.
For future discussions you can send me private mails (support@orbit.bio)
Regards,
Manuel
