### ISSUE TITLE
Running failed

### ISSUE THREAD

**Issue by yanglin526000** [mstritt/orbit-image-analysis#6]
d:\Eclipse\EclipseWorkSpace\orbit-image-analysis>java -XX:MaxPermSize=150m -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -cp "build/libs/orbit-image-analysis-3.08.jar;build/libs/lib/*" com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=150m; support was removed in 8.0
错误: 找不到或无法加载主类 com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis

The above is the error running log.I would be grateful if there could be a big god to help me solve it!!!

**Comment by mstritt** [comment]
Hi there,
where is the error log?
You just posted the start command (the MaxPermSize was removed info is ok, no problem).

**Comment by yanglin526000** [comment]
错误: 找不到或无法加载主类 .xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

Unfortunately, I didn't find the DocumentBuilderFactoryImpl file in the source project, which caused it to not work properly.

**Comment by yanglin526000** [comment]
Thank you, through the query data, I found a solution, DocumentBuilderFactoryImpl is JDK1.8 comes with an implementation class.
