### ISSUE TITLE
Suggested system requirements?

### ISSUE THREAD

**Issue by BootzenKatzen** [mstritt/orbit-image-analysis#7]
I find that Orbit runs really slowly on my computer.  It's my laptop for work, so it doesn't have anything fancy like a SSD or a ton of RAM.  It still works... but painfully slowly.  If you could post recommended system requirements somewhere, I think it would be very helpful, just so I could have an idea of what to look for in my next computer (whenever that opportunity comes around... likely never, but hey, I can dream)

**Comment by mstritt** [comment]
Hi @BootzenKatzen ,
thanks for using Orbit.
The system requirements are specified on the download page of Orbit:
http://www.orbit.bio/download/
Hope that helps!
Regards,
Manuel

**Comment by jfkotw** [comment]
@mstritt I guess this issue can be closed now.
